"""added preferences

Revision ID: 7f3dfa142109
Revises: 
Create Date: 2026-03-19 22:41:38.961914

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7f3dfa142109'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('holidays')
    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.alter_column('employee_id',
               existing_type=mysql.VARCHAR(length=20),
               nullable=True)
        batch_op.drop_index(batch_op.f('employee_id'))
        batch_op.drop_constraint(batch_op.f('fk_attendance_employee'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['employee_id'], ['employee_id'])

    with op.batch_alter_table('late_wallet', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('employee_id'))
        batch_op.create_unique_constraint('unique_wallet', ['employee_id', 'month', 'year'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dark_mode', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('email_notifications', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('push_notifications', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('attendance_alerts', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('leave_requests', sa.Boolean(), nullable=True))
        batch_op.alter_column('dob',
               existing_type=sa.DATE(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('dob',
               existing_type=sa.DATE(),
               nullable=False)
        batch_op.drop_column('leave_requests')
        batch_op.drop_column('attendance_alerts')
        batch_op.drop_column('push_notifications')
        batch_op.drop_column('email_notifications')
        batch_op.drop_column('dark_mode')

    with op.batch_alter_table('late_wallet', schema=None) as batch_op:
        batch_op.drop_constraint('unique_wallet', type_='unique')
        batch_op.create_index(batch_op.f('employee_id'), ['employee_id', 'month', 'year'], unique=True)

    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_attendance_employee'), 'users', ['employee_id'], ['employee_id'], onupdate='CASCADE', ondelete='CASCADE')
        batch_op.create_index(batch_op.f('employee_id'), ['employee_id', 'date'], unique=True)
        batch_op.alter_column('employee_id',
               existing_type=mysql.VARCHAR(length=20),
               nullable=False)

    op.create_table('holidays',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('date', sa.DATE(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
